<?php
//Site Settings
define("URL", "http://localhost");
define("API", "http://locahost/API");
//DB Settings
define("DB_HOST", "localhost");
define("DB_NAME", "GFW-Breaker");
define("DB_USERNAME", "Ender");
define("DB_PASSWORD", "Feng,HK,4778!");
define("PREFIX", 'main_');
//Email Settings
define("SMTP_SERVER_ADDR", "smtp.sina.com");
define("SMTP_SERVER_PORT", "25");
define("SMTP_USER_EMAIL", "f1991455223@sina.com");
define("SMTP_PASSWORD", "Feng,HK,4778!");
define("SMTP_USERNAME", "f1991455223@sina.com");
//Security Settings
define('MAX_SIGN_LIFETIME', 3);
define('PASSWORD_SALT', '8f76ebaf6bf52191727147ebf46dbf3a');
define('MAX_SIGN_LIVE', 5);